from slices.core import SLICES
from pymatgen.core.structure import Structure
from pymatgen.analysis.structure_matcher import StructureMatcher, ElementComparator
# obtaining the pymatgen Structure instance of Sr3Ru2O7
original_structure = Structure.from_file(filename='Sr3Ru2O7.cif')
# creating an instance of the InvCryRep Class (initialization)
backend=SLICES(graph_method='econnn')
# converting a crystal structure to its SLICES string and perform data augmentation (with random atom order) (5x)
slices_list=backend.structure2SLICESAug_atom_order(structure=original_structure,strategy=4,num=50) 
slices_list_unique=list(set(slices_list))
#print(slices_list_unique)
cannon_slices_list=[]
for i in slices_list_unique:
    cannon_slices_list.append(backend.get_canonical_SLICES(i,strategy=3))
# test get_canonical_SLICES
print(len(slices_list),len(set(cannon_slices_list)))
#print(cannon_slices_list)
# 5 SLICES generated by data augmentation has been reduced to 1 canonical SLICES
